### PR TITLE
Mpi pull request

### PR DESCRIPTION
**Pull request by LennardMiller**
Compared a (not very) turbulent mpi run with a run from the old model, statistics look the same but the runs don't show exactly the same behaviour (perhaps because of the slightly different time-stepping). 

Anyway this first mpi version should be able to be used to perform future runs on PSMN and hence replace the old basilisk code from now on.

### CODE REVIEW

**Comment by bderembl** [comment]
@LennardMiller 
Take a look at the changes. the main modif is that `NX` and `NY` are now global size (and also what you need to set in params.in). `Nx` and `Ny` remain local indices. 

went back to a simpler netcdf_io. not optimal but easier to read. We'll have to move on to pnetcdf at some point anyway

**Comment by bderembl** [comment]
printing is also simpler with only proc 0 printing by default

**Comment by LennardMiller** [comment]
At a first glance it looks good, I'm glad you managed to remove a lot of the #ifdef _MPI. I'm guessing it deserves the name 'significant cleanup'. I'll have a closer look tomorrow.

Btw did you try to run the code in single proc as well? And is there anything else we need to test? 

I found out how to profile the code at PSMN in lyon, would be the next step to see if it's worth implementing Thomas algorithm/remove FFTW's transposition in fourier space.

**Comment by bderembl** [comment]
@LennardMiller 
added preliminary support for a restart file. it should work in mpi. note that the variable of interest for a restart is now q instead of psi.

all of this must be documented

.. of course.

**Comment by LennardMiller** [comment]
I added two parameters in the creation of the MPI FFTW plans (FFTW_DESTROY_INPUT|FFTW_MPI_TRANSPOSED_OUT), the first slightly accelerates the computation of the fourier transform and the second cuts the communication time by two by avoiding a backtransposition in fourier space.

Even with reduced communication the code doesn't scale super well, but that was to be expected given the domain decomposition. The gain from 16 processors to 64 processors for a 512x512 simulation is only a factor of two, and at 64 processors (i.e. 8 grid lines per processor) the total computation time is shared roughly 50/50 between real computations and mpi communications. Therefore I'd say it makes sense to run this code at his gridline/proc setting, as I don't want to run a code that spends more time communicating than computing (also the tendency for the same gridlines/proc at increasing total number of gridpoints suggests that the MPI time percentage increases at high resolution, so perhaps even less grid lines per proc would be adequate). 

It also looks like its not worth it to implement the Thomas algorithm. Roughly half of the real computation time (i.e. without MPI) is spent in the inversion, and replacing one of the FFTs would mean we could at best reduce this by another factor of two, reducing the real computation time by 25%. For me the bottleneck seems to be the MPI time, and I don't think this gain is significant enough to make the effort. 

I went over the whole code again and I'm quite happy with what it looks like now, so for me we could merge this branch with the main (I still need to modify the stochastic forcing to work in MPI but I will do this at some point later). 

Do we need a doc file for the mpi part?

**Comment by bderembl** [comment]
I tried to reduce the number of arrays for fftw. should we try inplace fft? as suggested in 
https://www.fftw.org/fftw3_doc/FFTW-MPI-Performance-Tips.html

that would be only one temporary array

**Comment by bderembl** [comment]
after your tests for the BC in MPI, we should merge

**Pull request merged**
