### PR TITLE
Stochastic forcing

### PR DESCRIPTION
**Pull request by LennardMiller**

### CODE REVIEW

**Comment by bderembl** [comment]
@LennardMiller 

Here are a couple of suggestions:

- do not keep params.in in the gihub repo. instead, one should keep several params.in in the test repo which should be for some specific (test) configuration

- Adaptive Adams Bashforth for Stochastic differential equations is not so simple. (see https://arxiv.org/pdf/1610.08417.pdf). I propose that we keep AB for the deterministic part and use an euler-maruyama scheme for the stochastic part. I try to motivate this in the doc.

- hence the stochastic component should really appear only in timestep.h

- also see the preliminary documentation

**Comment by LennardMiller** [comment]
Agree with all of your points (the details of stochastic differential equations are beyond me so I trust you on this one).

I added a little python script that takes a simulation run with params_02.in to confirm that we inject the right amount of energy (and enstrophy). To be honest if this roughly agrees with what we expect I think we can be happy with this part of the code for now then. I'm suggesting to merge so that you can continue with the multilayer case.

**Comment by bderembl** [comment]
@LennardMiller 
could you double check that

- [ ] The shape of the envelope is correct both in the documentation and in `forcing.h`
- [ ] Please elaborate in the documentation for this shape of forcing
- [ ] Some indices look weird to me, especially at the end of the forcing generation: 

```
  for(int j = 0; j<Ny; j++){
    for(int i = 0; i<Nx; i++){
      forc[idx(i,j)] = out[c_idx(i,j)];
    }
  }
```

you are forcing at `i = 0` and `j = 0` which are boundary points??

- [ ] please also double check the last two loops and provide some comments
- [ ] I changed your notation for $\epsilon^2$ -> $\sigma_f$
- [ ] also to be consistent I use the forcing wave number variable `k_f`
- [ ] add comments either in the documentation or your python script for your verification tests

**Comment by LennardMiller** [comment]
@bderembl 
Regarding the forcing at the boundaries,  I thought it won't make a difference as the boundary values are not used to inverse the laplacian and are fully set by the boundary conditions at the next iteration anyway. Is there a problem here? I would prefer to guard this structure of the forcing as it would be viable for the periodic case, and making it respect the boundary conditions would mean having to opt for a sin-basis instead which I would like to avoid. (Also, the classical Munk forcing has non-zero values at the eastern and western boundaries and that doesn't pose a problem right?) Maybe I missed something here though.

I added some explanation for the new variables in the doc, and added comments in forcing.h . Let me know what you think.

**Pull request merged**
